let dataCentros = [
    {
        codigo: "c01",
        nombre: "Hospital de Niños Dr. Ricardo Gutiérrez",
        direccion: "Gallo 1330",
        barrio: "Recoleta",
        telefono: "011 4962-9247",
        img: "./img/logo_gutierrez.jpg",
    },
    {
        codigo: "c02",
        nombre: "Hospital General de Agudos Dr. T. Álvarez",
        direccion: "Doctor Juan Felipe Aranguren 2701",
        barrio: "Flores",
        telefono: "011 4630 2900",
        img: "./img/logp-alvarez.png",
    },
    {
        codigo: "c03",
        nombre: "Hospital de Pediatría S.A.M.I.C. Prof. Dr. Juan P. Garrahan",
        direccion: "Combate de los Pozos 1881",
        barrio: "Constitución",
        telefono: "(+54 11) 4122-6000",
        img: "./img/logoGarrahan.png",
    },
    {
        codigo: "c04",
        nombre: "Hospital Pedro de Elizalde",
        direccion: "Manuel A. Montes de Oca 40",
        barrio: "Constitución",
        telefono: "4363-2100 al 2200",
        img: "./img/logo-elizalde.jpg",
    },
    {
        codigo: "c04",
        nombre: "Hospital Infanto Juvenil C. Tobar García",
        direccion: "Doctor Ramón Carrillo 315",
        barrio: "Barracas",
        telefono: "4305-6178",
        img: "./img/HCTG.jpeg",
    },
    {
        codigo: "c05",
        nombre: "Hospital Materno Infantil R. Sardá",
        direccion: "Esteban de Luca 2151",
        barrio: "Parque Patricios",
        telefono: "4943-3567",
        img: "./img/logo-sarda.jpg",
    },
    {
        codigo: "c06",
        nombre: "Hospital de Odontología Infantil Don Benito Quinquela Martín",
        direccion: "Don Pedro de Mendoza 1795",
        barrio: "La Boca",
        telefono: "4301-4834 / 4870 / 4302-9510",
        img: "./img/logo-quinquela.png",
    },
    {
        codigo: "c07",
        nombre: "ITEBA - Instituto de Terapias Especializadas de Buenos Aires",
        direccion: "Terrada 550",
        barrio: "Flores",
        telefono: "(011) 4611-2647",
        img: "./img/clinica-iteba.jpg",
    },
    {
        codigo: "c08",
        nombre: "FLENI",
        direccion: "Montañeses 2325",
        barrio: "Belgrano",
        telefono: "(011) 5777-3200",
        img: "./img/logo-fleni.jpg",
    },
    {
        codigo: "c09",
        nombre: "INECO",
        direccion: "Marcelo T. de Alvear 1632",
        barrio: "Palermo",
        telefono: "0810-266-4203",
        img: "./img/logo-ineco.png",
    }
];